/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i loginterface.h -i QtZeitgeist/DataModel/Event -i QtZeitgeist/DataModel/TimeRange -p :loginterface.cpp ../xml/org.gnome.zeitgeist.Log.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "loginterface.h"
#include "QtZeitgeist/DataModel/Event"
#include "QtZeitgeist/DataModel/TimeRange"
/*
 * Implementation of interface class OrgGnomeZeitgeistLogInterface
 */

OrgGnomeZeitgeistLogInterface::OrgGnomeZeitgeistLogInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGnomeZeitgeistLogInterface::~OrgGnomeZeitgeistLogInterface()
{
}

