/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -i QtZeitgeist/DataModel/Event -i QtZeitgeist/DataModel/TimeRange -a monitoradaptor.h: ../xml/org.gnome.zeitgeist.Monitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MONITORADAPTOR_H_1292508978
#define MONITORADAPTOR_H_1292508978

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "QtZeitgeist/DataModel/Event"
#include "QtZeitgeist/DataModel/TimeRange"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.gnome.zeitgeist.Monitor
 */
class MonitorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.gnome.zeitgeist.Monitor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.gnome.zeitgeist.Monitor\">\n"
"    <!-- Client side monitor installed on the engine with\n"
"         org.gnome.zeitgeist.Log.InstallMonitor() -->\n"
"    <method name=\"NotifyInsert\">\n"
"      <!-- Events matching the templates has been inserted into the log -->\n"
"      <annotation value=\"QtZeitgeist::DataModel::TimeRange\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <annotation value=\"QtZeitgeist::DataModel::EventList\" name=\"com.trolltech.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"(xx)\" name=\"time_range\"/>\n"
"      <arg direction=\"in\" type=\"a(asaasay)\" name=\"events\"/>\n"
"    </method>\n"
"    <method name=\"NotifyDelete\">\n"
"      <!-- Events matching the templates has been deleted from the log -->\n"
"      <annotation value=\"QtZeitgeist::DataModel::TimeRange\" name=\"com.trolltech.QtDBus.QtTypeName.In0\"/>\n"
"      <annotation value=\"QtZeitgeist::DataModel::EventIdList\" name=\"com.trolltech.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"(xx)\" name=\"time_range\"/>\n"
"      <arg direction=\"in\" type=\"au\" name=\"event_ids\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    MonitorAdaptor(QObject *parent);
    virtual ~MonitorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void NotifyDelete(const QtZeitgeist::DataModel::TimeRange &time_range, const QtZeitgeist::DataModel::EventIdList &event_ids);
    void NotifyInsert(const QtZeitgeist::DataModel::TimeRange &time_range, const QtZeitgeist::DataModel::EventList &events);
Q_SIGNALS: // SIGNALS
};

#endif
